# https://nx.dev/recipes/nx-release/publish-in-ci-cd
name: Publish

on:
  # Use the release event because push events are not triggered for commits tagged with more than three tags:
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#push.
  release:
    types: [created]

jobs:
  test:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # needed for provenance data generation
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
          registry-url: https://registry.npmjs.org/

      - run: npm ci

      - run: npx nx report

      - run: npx nx release publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
