name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write # needed for provenance data generation

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          # Need full git history for nx release to work properly
          fetch-depth: 0
          filter: tree:0
          token: ${{ secrets.PAT }}

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
          registry-url: https://registry.npmjs.org/

      - run: npm ci

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - run: npx nx release --skip-publish
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }} # Needed for pushing release commits.

      - run: npx nx release publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
